# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcat',
            name='caty',
        ),
        migrations.AddField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='productos.Subcat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='productos.Category'),
        ),
    ]
